spring.data.mongodb.uri=mongodb://citadel:citadel123@localhost:27017/citadel_db
spring.data.mongodb.database=citadel_db
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-3level %logger{39} - %msg%n